### ISSUE TITLE
Link to rendered slides for `introduction to Rust` is outdated

### ISSUE THREAD

**Issue by BriocheBerlin** [ferrous-systems/training-bookshelf#2]
https://github.com/ferrous-systems/training-bookshelf/blob/main/ferrous-systems.github.io/teaching-material/index.html gets a 404.

**Comment by jonathanpallant** [comment]
Closed by https://github.com/ferrous-systems/training-bookshelf/commit/e071fcdc9c67f0900333917f19a9895b7f747a39
